

```java
package com.thd.ordermanagement.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * JPA Entity representing an Order in the THD Order Management Service.
 * 
 * This entity maps to the "orders" table and stores order information
 * including the order status, which is used by the order count summary
 * endpoint (GET /api/v1/orders/summary/counts) to group and count orders
 * by their current {@link OrderStatus}.
 */
@Entity
@Table(name = "orders")
public class Order {

    /**
     * Unique identifier for the order, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private Long id;

    /**
     * External-facing order number for customer reference.
     */
    @Column(name = "order_number", unique = true, nullable = false, length = 50)
    @NotNull(message = "Order number is required")
    private String orderNumber;

    /**
     * Name of the customer who placed the order.
     */
    @Column(name = "customer_name", nullable = false, length = 255)
    @NotNull(message = "Customer name is required")
    private String customerName;

    /**
     * Email address of the customer.
     */
    @Column(name = "customer_email", nullable = false, length = 255)
    @NotNull(message = "Customer email is required")
    private String customerEmail;

    /**
     * Current status of the order.
     * This field is central to the order count summary feature — the summary
     * endpoint groups orders by this status and returns counts per bucket.
     * 
     * @see OrderStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @NotNull(message = "Order status is required")
    private OrderStatus status;

    /**
     * Total monetary amount for the order.
     */
    @Column(name = "total_amount", nullable = false, precision = 12, scale = 2)
    @NotNull(message = "Total amount is required")
    private BigDecimal totalAmount;

    /**
     * Shipping address for the order.
     */
    @Column(name = "shipping_address", nullable = false, length = 500)
    @NotNull(message = "Shipping address is required")
    private String shippingAddress;

    /**
     * Timestamp when the order was created. Automatically set on persist.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the order was last updated. Automatically set on persist and update.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Default no-args constructor required by JPA.
     */
    public Order() {
    }

    /**
     * Parameterized constructor for creating a new Order with all required fields.
     *
     * @param orderNumber     the external-facing order number
     * @param customerName    the name of the customer
     * @param customerEmail   the email address of the customer
     * @param status          the current order status
     * @param totalAmount     the total monetary amount
     * @param shippingAddress the shipping address
     */
    public Order(String orderNumber, String customerName, String customerEmail,
                 OrderStatus status, BigDecimal totalAmount, String shippingAddress) {
        this.orderNumber = orderNumber;
        this.customerName = customerName;
        this.customerEmail = customerEmail;
        this.status = status;
        this.totalAmount = totalAmount;
        this.shippingAddress = shippingAddress;
    }

    /**
     * Lifecycle callback to set timestamps before the entity is first persisted.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        // Default status to PENDING if not explicitly set
        if (this.status == null) {
            this.status = OrderStatus.PENDING;
        }
    }

    /**
     * Lifecycle callback to update the modified timestamp before each update.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getShippingAddress() {
        return shippingAddress;
    }

    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    // -------------------------------------------------------------------------
    // equals, hashCode, and toString
    // -------------------------------------------------------------------------

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return Objects.equals(id, order.id) &&
               Objects.equals(orderNumber, order.orderNumber);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, orderNumber);
    }

    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", orderNumber='" + orderNumber + '\'' +
                ", customerName='" + customerName + '\'' +
                ", customerEmail='" + customerEmail + '\'' +
                ", status=" + status +
                ", totalAmount=" + totalAmount +
                ", shippingAddress='" + shippingAddress + '\'' +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
```